### ISSUE TITLE
can we publish this for @postfinance?

### ISSUE THREAD

**Issue by bbortt** [postfinance/ngx-ace-editor-wrapper#1]
we were using this package in an Angular 9 implementation, see [tavwizard/ace-editor-ng9](https://github.com/tavwizard/ace-editor-ng9). but they did not plan to update to Angular 10, neither would their naming allow it. so I did. it's now published to npmjs, named [`@bbortt/ngx-ace-editor-wrapper`](https://www.npmjs.com/package/@bbortt/ngx-ace-editor-wrapper).

I think it would be cool to maintain it here, not in my personal repositories. then publishing it named `@postfinance/ngx-ace-editor-wrapper`. it does also show that we are not only working on golang stuff ;) what do you think? asking @imathu.

cc: @boskoop.

**Comment by imathu** [comment]
@bbortt: to show, that we are not only working on golang stuff is great. I see no problem to push that on postfinance repo if you don't break any license issues

**Comment by bbortt** [comment]
@imathu fyi our first package was published to [@postfinance/ngx-ace-editor-wrapper](https://www.npmjs.com/package/@postfinance/ngx-ace-editor-wrapper)  :rocket: it's currently in `beta` and will be released as soon as we tested everything through.
